sudo: required
language: go
services:
- docker
go:
- 1.10.2
go_import_path: eva
before_install:
- chmod +x release
- chmod +x build
install:
- ./release
script:
- docker build --rm -t kubesphere/eva .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push kubesphere/eva;
  fi