#!/usr/bin/env bash

echo "Release alpine version ..."
mkdir -p bin/alpine
docker build -t go_alpine_builder -f Dockerfile.build.alpine .
docker run -ti --rm -v $(pwd):/app go_alpine_builder ./build bin/alpine/evasvc
tar -C bin/alpine/ -czf bin/alpine/evasvc-alpine-amd64.tar.gz evasvc

ls -lh bin/*